<?php

/**
 * @file accessible_slider_example.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_image_default_styles().
 */

function accessible_slider_example_image_default_styles() {
  $styles = array();

  // Exported image style: s51_slider_style.
  $styles['as_slider_style'] = array(
    'name' => 'as_slider_style',
    'label' => 'Slider Image',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 800,
          'height' => 450,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/**
 * Implements hook_views_api().
 */
function accessible_slider_example_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}